### ISSUE TITLE
1.16 Checklist

### ISSUE THREAD

**Issue by Flo56958** [Flo56958/MineTinker#137]
- [x] Add Netherrite Items
- [x] Add new Enchantments
- [x] Add Nether Gold Ore to Auto-Smelt
