### ISSUE TITLE
Split ModManager into two Classes

### ISSUE THREAD

**Issue by Flo56958** [Flo56958/MineTinker#150]
The ModManager Class is way too bloated. As the name suggests it should handle all Modifiers. But it handles almost everything related to Items. That should not be task of the ModManager

- [ ] Split ModManager into ModManager and ItemManager
- [ ] Add RewriteLore Event (or Observer on Lore change) to easily know when to rewrite the Lore
- [ ] #149: Add Reload-Listener to reload on Event
- [ ] Make the Pattern Matcher its own Class and add tests to test it

**Tasks of the *ModManager*:**
- Register and unregister Modifiers
- Manage enabled and disabled Modifiers
- Apply Modifiers to Tools and Armor
- Manage Modifiers on Items (Levels, Application, Removal)
- Settings are in Modifiers.yml

**Tasks of the *ItemManager*:**
- Convert ItemStacks
- Manage ItemStacks (Exp, Level, Identifier, Core-Tags, Rewrite Lore)
- Manage Lore (layout.yml)

ItemManager and ModManager should work hand in hand like two modules but separated enough that they are two separate classes that do not overlap in function.
